name: Tests

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [created]

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Update CHANGELOG')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup project
        uses: ./.github/workflows/setup-project

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Compile assets
        run: npm run build

      - name: Prepare application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run coverage checks
        run: composer coverage && composer type-coverage

      - name: Run tests
        run: composer test
